site_name: copairs
site_description: Find pairs and compute metrics between them
repo_url: https://github.com/cytomining/copairs

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search
  - section-index
  - mkdocs-jupyter:
      include_source: false
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true
            show_object_full_path: false
            heading_level: 2
            show_root_heading: true
            docstring_section_style: list
            docstring_style: numpy
            show_source: true            

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Examples:
      - Overview: examples/README.md
      - Finding Pairs: examples/finding_pairs.ipynb
      - Phenotypic Activity: examples/phenotypic_activity.ipynb
      - Phenotypic Consistency: examples/phenotypic_consistency.ipynb
      - Null Size Estimation: examples/null_size.ipynb
  - API Reference:
      - Overview: api/index.md
      - matching: api/matching.md
      - compute: api/compute.md
      - map: api/map.md
      - replicating: api/replicating.md
      - plot: api/plot.md