"""Tests for the AUC p-value computation function generated by the CLI."""

import time

import numpy as np
import pytest
import scipy.stats as stats
from scipy.stats import mannwhitneyu

from copairs.compute import compute_auc_pvalues


def test_compute_auc_pvalues_exact():
    """Test accuracy against scipy.stats.mannwhitneyu (method='exact')."""
    # Small sample, integer U
    n1, n2 = 10, 10
    x = np.arange(n1, n1 + n2)
    y = np.arange(n1)
    stat, p_scipy = stats.mannwhitneyu(x, y, alternative="greater", method="exact")

    p_ours = compute_auc_pvalues([stat], [n1], [n1 + n2])[0]
    assert np.allclose(p_scipy, p_ours)

    # Another test case, intermediate U
    x = [1, 3, 5, 7, 9]
    y = [0, 2, 4, 6, 8]
    n1, n2 = 5, 5
    stat, p_scipy = stats.mannwhitneyu(x, y, alternative="greater", method="exact")
    p_ours = compute_auc_pvalues([stat], [n1], [n1 + n2])[0]
    assert np.allclose(p_scipy, p_ours)


def test_compute_auc_pvalues_asymptotic():
    """Test large regime against scipy.stats.mannwhitneyu (method='asymptotic')."""
    n1, n2 = 100, 100
    x = np.random.default_rng(42).standard_normal(n1) + 0.1
    y = np.random.default_rng(42).standard_normal(n2)
    stat, p_scipy = stats.mannwhitneyu(x, y, alternative="greater", method="asymptotic")
    p_ours = compute_auc_pvalues([stat], [n1], [n1 + n2])[0]
    assert np.allclose(p_scipy, p_ours)


def test_compute_auc_pvalues_edge_cases():
    """Test edge cases for U scores."""
    n1, n2 = 5, 5
    n_total = n1 + n2

    # U larger than max
    p = compute_auc_pvalues([30], [n1], [n_total])[0]
    assert p == 0.0

    # U smaller than 0
    p = compute_auc_pvalues([-1], [n1], [n_total])[0]
    assert p == 1.0

    # Non-integer U (from ties)
    # If U = 12.5, P(U >= 12.5) = P(U >= 13)
    p_12_5 = compute_auc_pvalues([12.5], [n1], [n_total])[0]
    p_13 = compute_auc_pvalues([13], [n1], [n_total])[0]
    assert p_12_5 == p_13


def test_compute_auc_pvalues_zero_samples():
    """Test cases with zero positive or negative samples."""
    # n_pos = 0
    p = compute_auc_pvalues([0], [0], [10])[0]
    assert p == 1.0

    # n_neg = 0 (n_pos = n_total)
    p = compute_auc_pvalues([0], [10], [10])[0]
    assert p == 1.0


def test_compute_auc_pvalues_vectorized():
    """Test vectorized input with mixed configurations."""
    u_scores = [15, 5728, 0]
    n_pos = [5, 100, 5]
    n_total = [10, 200, 10]
    p_vals = compute_auc_pvalues(u_scores, n_pos, n_total)

    assert len(p_vals) == 3
    # Check individual results
    assert np.allclose(p_vals[0], compute_auc_pvalues([15], [5], [10])[0])
    assert np.allclose(p_vals[1], compute_auc_pvalues([5728], [100], [200])[0])
    assert np.allclose(p_vals[2], compute_auc_pvalues([0], [5], [10])[0])


@pytest.mark.parametrize(
    "n_pos, n_total, u_stat, expected_pval",
    [
        # Small regimes where exact DP should be triggered
        (
            4,
            9,
            20,
            0.0079365,
        ),  # 4 pos, 5 neg, U=20 (perfect separation). p = 1 / binom(9,4) = 1/126
        (
            3,
            7,
            12,
            0.0285714,
        ),  # 3 pos, 4 neg, U=12 (perfect). p = 1 / binom(7,3) = 1/35
        (
            4,
            24,
            80,
            9.410878976096367e-05,
        ),  # 4 pos, 20 neg, U=80 (perfect). p = 1 / binom(24,4)
        (4, 24, 70, 0.008846226237530584),  # 4 pos, 20 neg, U=70 (partial overlap)
    ],
)
def test_exact_small_regime(n_pos, n_total, u_stat, expected_pval):
    """Test that the DP exact method perfectly matches known combinatorial probabilities."""
    u_scores = np.array([u_stat])
    n_pos_arr = np.array([n_pos])
    n_total_arr = np.array([n_total])

    # Call your generated function
    pvals = compute_auc_pvalues(u_scores, n_pos_arr, n_total_arr)

    # Assert
    np.testing.assert_allclose(pvals[0], expected_pval, rtol=1e-5)


def test_asymptotic_large_regime():
    """Test that large sample approximations match SciPy's asymptotic method."""
    n_pos = 50
    n_neg = 2000
    n_total = n_pos + n_neg

    # Generate random scores
    np.random.seed(42)
    pos_scores = np.random.normal(loc=1.0, scale=1.0, size=n_pos)
    neg_scores = np.random.normal(loc=0.0, scale=1.0, size=n_neg)

    # Get ground truth from SciPy
    res = mannwhitneyu(
        pos_scores, neg_scores, alternative="greater", method="asymptotic"
    )
    u_stat = res.statistic
    expected_pval = res.pvalue

    u_scores = np.array([u_stat])
    n_pos_arr = np.array([n_pos])
    n_total_arr = np.array([n_total])

    pvals = compute_auc_pvalues(u_scores, n_pos_arr, n_total_arr)
    np.testing.assert_allclose(pvals[0], expected_pval, rtol=1e-3)


def test_hybrid_batch_processing():
    """Test that the function correctly splits, processes, and recombines a mixed batch."""
    # Mix of small (exact) and large (asymptotic) configurations
    n_pos_arr = np.array([4, 50, 3, 100])
    n_total_arr = np.array([24, 2050, 7, 5100])

    # U-stats: Perfect for smalls, average for larges
    u_scores = np.array(
        [
            4 * 20,  # Exact: Perfect separation
            50 * 2000 * 0.8,  # Asymptotic: AUC = 0.8
            3 * 4,  # Exact: Perfect separation
            100 * 5000 * 0.9,  # Asymptotic: AUC = 0.9
        ]
    )

    # Run the batch
    pvals = compute_auc_pvalues(u_scores, n_pos_arr, n_total_arr)

    # Verify shape and bounds
    assert pvals.shape == (4,)
    assert np.all((pvals >= 0.0) & (pvals <= 1.0))

    # We know indices 0 and 2 should match exact combinations
    np.testing.assert_allclose(pvals[0], 1.0 / 10626, rtol=1e-5)  # binom(24, 4)
    np.testing.assert_allclose(pvals[2], 1.0 / 35, rtol=1e-5)  # binom(7, 3)


def test_extreme_u_values():
    """Test behavior when AUC is exactly 0.5 or 1.0 to ensure no math domain errors."""
    n_pos_arr = np.array([10, 10])
    n_total_arr = np.array([110, 110])

    u_max = 10 * 100
    u_mid = u_max / 2

    u_scores = np.array([u_max, u_mid])

    pvals = compute_auc_pvalues(u_scores, n_pos_arr, n_total_arr)

    # Max U should be highly significant (p < 0.05)
    assert pvals[0] < 0.001
    # Mid U (AUC=0.5) should be completely insignificant (p ~ 0.5)
    np.testing.assert_allclose(pvals[1], 0.5, atol=0.05)


def test_compute_auc_pvalues_scalability():
    """Test scalability with 10K different configurations and compare accuracy with scipy."""
    n_configs = 10000
    rng = np.random.default_rng(42)

    # Generate 10K configurations
    # Mixed regimes: some small (DP), some large (Asymptotic)
    # n_pos from 1 to 100
    # n_total from n_pos + 1 to 200
    n_pos = rng.integers(1, 100, size=n_configs)
    n_neg = rng.integers(1, 100, size=n_configs)
    n_total = n_pos + n_neg

    # Generate random U scores within valid range [0, n_pos * n_neg]
    u_scores = rng.random(size=n_configs) * (n_pos * n_neg)

    print(f"\nComputing p-values for {n_configs} configurations...")
    start_time = time.time()
    p_ours = compute_auc_pvalues(u_scores, n_pos, n_total)
    duration = time.time() - start_time
    print(f"Duration: {duration:.4f} seconds")

    # Verify a subset of 100 random configurations against scipy for correctness
    print("Verifying 100 random samples against scipy.stats.mannwhitneyu...")
    sample_indices = rng.choice(n_configs, size=100, replace=False)

    for idx in sample_indices:
        u = u_scores[idx]
        n1 = int(n_pos[idx])
        n2 = int(n_neg[idx])
        nt = int(n_total[idx])

        # Decide which method scipy should use based on our threshold
        is_small = (n1 * n2 <= 10000) and (max(n1, n2) <= 50)

        if is_small:
            # Exact MW using dummy arrays with no ties
            x = rng.standard_normal(n1)
            y = rng.standard_normal(n2)
            res = stats.mannwhitneyu(x, y, alternative="greater", method="exact")
            u_scipy = res.statistic
            p_scipy = res.pvalue
            p_val_ours = compute_auc_pvalues([u_scipy], [n1], [nt])[0]
            assert np.allclose(p_val_ours, p_scipy, atol=1e-10), (
                f"Exact mismatch at n1={n1}, n2={n2}, U={u_scipy}"
            )
        else:
            # Asymptotic
            mu = n1 * n2 / 2.0
            std = np.sqrt(n1 * n2 * (n1 + n2 + 1) / 12.0)
            z = (u - 0.5 - mu) / std
            p_scipy = stats.norm.sf(z)
            assert np.allclose(p_ours[idx], p_scipy, atol=1e-10), (
                f"Asymptotic mismatch at n1={n1}, n2={n2}, U={u}"
            )


def test_extreme_regimes():
    """Test very small and large n_pos/n_total."""
    # High n_total, low n_pos
    n_pos = np.array([1, 1, 5])
    n_total = np.array([1000, 10000, 10000])
    u_scores = np.array([500, 5000, 25000])
    p_vals = compute_auc_pvalues(u_scores, n_pos, n_total)
    assert len(p_vals) == 3
    for p in p_vals:
        assert 0 <= p <= 1

    # High n_pos, high n_total
    n_pos = np.array([5000, 10000])
    n_total = np.array([10000, 20000])
    u_scores = np.array([12500000, 50000000])  # roughly mu
    p_vals = compute_auc_pvalues(u_scores, n_pos, n_total)
    assert np.allclose(p_vals, 0.5, atol=1e-2)
