# Configuration for phenotypic consistency analysis
# Matches the phenotypic_consistency.ipynb example

data:
  path: "../data/2016_04_01_a549_48hr_batch1_plateSQ00014812.csv"
  metadata_regex: "^Metadata"

preprocessing:
  # Filter to only active compounds based on activity analysis
  # Note: This requires first running the activity analysis
  # The notebook uses the activity_map.csv file to filter active compounds
  # Since we can't load external CSV in YAML, we'll need to handle this differently
  
  # Remove rows with missing targets (implicit in notebook via query)
  - type: dropna
    columns: ["Metadata_target"]
  
  # Split the pipe-separated target values into lists for multilabel analysis
  - type: split_multilabel
    column: "Metadata_target"
    separator: "|"

average_precision:
  # Use multilabel since compounds have multiple targets (separated by |)
  multilabel: true
  
  params:
    # Positive pairs: compounds sharing the same target
    pos_sameby: ["Metadata_target"]
    pos_diffby: []
    
    # Negative pairs: compounds with different targets
    neg_sameby: []
    neg_diffby: ["Metadata_target"]
    
    # For multilabel analysis, specify the column
    multilabel_col: "Metadata_target"

mean_average_precision:
  sameby: ["Metadata_target"]  # Group by target
  null_size: 1000000           # As used in notebook
  threshold: 0.05
  seed: 0                      # As used in notebook

output:
  path: "../../data/target_maps_runner.csv"
  save_ap_scores: false