name: Deploy docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies with uv
        run: |
          uv sync --extra docs
          uv pip install -e .
      
      - name: Build documentation
        run: |
          export JUPYTER_PLATFORM_DIRS=1
          uv run mkdocs build --strict
      
      - name: Upload build artifacts (for PRs)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: site/
      
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export JUPYTER_PLATFORM_DIRS=1
          uv run mkdocs gh-deploy --force